PROD-2756: upgrade dependencies and compiler version
cto-ai/sdk-bash pull request #7
Opened 2023-05-10 19:20 UTC by jossemargt-cto-ai

There was an opportunity to get up to date with the latest Rust compiler (1.69.x). To achieve this, I had to update some dependencies and fix some minor complaints from the compiler around our codebase.

2023-05-17 18:30 UTC, nitishkumar71 approved these changes

2023-05-17 21:26 UTC, NickAnderegg requested changes
Some minor edits to the text in CONTRIBUTING.md

2023-05-17 21:26 UTC, NickAnderegg commented on CONTRIBUTING.md
> +using `cargo build` should suffice.
```suggestion
The Bash SDK binaries are automatically built and packaged as `tar.gz` by the
GitHub Workflows within this repository, on every pushed commit. The build logic is
distributed across the `scripts/build*` scripts, which make use of `docker buildx` to
cross compile the binaries. However, for local development, using `cargo build` should suffice.
```

2023-05-17 21:26 UTC, NickAnderegg commented on CONTRIBUTING.md
> +resulting artifacts will be published within the GitHub **Releases** section.
```suggestion
When the master branch is tagged with a new version (which must match the
version in the root `Cargo.toml` configuration), a new release is built. The
resulting artifacts will be published through the **Releases** of this repo.
```

2023-05-17 21:26 UTC, NickAnderegg commented on CONTRIBUTING.md
> +
```suggestion
This Bash SDK is a group of binaries enabling users to interact with the CTO.ai
API within their workflows. These binaries are written in Rust, so using `cargo`
for the development cycle should suffice; however, we would like to share some
details to help you with your contribution.

```

2023-05-18 16:21 UTC, NickAnderegg approved these changes
lgtm

2023-05-18 17:24 UTC, merged